### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ts-3156** [ts-3156/egotter#107]
- [x] add sequence on unfriends and unfollowers
  - [x] reverse the order
- [x] verify relationships
  - [x] friendships, followerships, friends_size and followers_size
- [x] do not print `xxx is not found`
  - [ ] use papertrail
  - [x] cache 404 errors
- [x] set unauthorized flag in `CreateNotificationMessageWorker`
