### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ts-3156** [ts-3156/egotter#116]
- each result pages
- run a bg batch when seeing each result pages
- improve word cloud

**Comment by ts-3156** [comment]
- [ ] スポットインスタンスの価格取得、autoscalingへの設定反映
- [ ] statusesはtruncateして、アクセスがあったらjobで復旧する
- [ ] 結果ページの真ん中にもadsenseを追加(縦のサイズをアドセンスと揃える)
- [ ] リンクをまとめサイトと同じフォーマットにする

**Comment by ts-3156** [comment]
- [ ] medium web2, medium sidekiq5 を作る。secondary2を止める
- [x] build_login_userのバグ修正
- [ ] リム通知の作り込み
- [x] ImportTwitterUserRelationsを同期実行にする
- [x] enqueued_at, ... を他のワーカーでも記録する
- [ ] エラー数メトリクスを送信する

**Comment by ts-3156** [comment]
- [ ] stale?を使う 各メニューページ
- [ ] close_friendships対応
- [ ] statuses, favorites対応
- [ ] 3日間未ログインにログインを促す
- [ ] 自動読み込みをやめてadsenseを表示する
- [ ] 四角いリンクフォーマットを利用する

**Comment by ts-3156** [comment]
- [ ] friendshipを削除する
- [ ] twitter_db_statuses
- [ ] リム通知が正しく送られているかチェックする仕組みを作る
- [ ] デフォルトのDMの返事を作る
- [ ] 質問ページを更新する
- [ ] 並列度を上げる→apiエラーをなくす、dead lockをなくす
- [ ] 結果が0の場合のメッセージを改善する

- [ ] close_friends_controller
- [ ] 広告ユニットをデバイスタイプで分ける
- [ ] 新規ユーザー数と検索数は釣り合っている？

**Comment by ts-3156** [comment]
twitter_user_idを引数で渡す
async: falseの場合は引数で値を渡す
persist!の中でリトライする

**Comment by ts-3156** [comment]
- [ ] リムられページへのアクセスでもワーカー追加
- [ ] 未ログインで複数検索した場合はログインボタンを表示
- [ ] 通知のリファクタリング、無駄な送信とログ作成をやめる(PromptReport, SearchReport)

**Comment by ts-3156** [comment]
- [ ] users.rake, repair.rakeを今のAPIに合わせて作り直す
- [ ] Import... でsuspendedなユーザーを作成する
